name       : osm-gps-map
version    : 1.2.0
release    : 7
source     :
    - https://github.com/nzjrs/osm-gps-map/releases/download/1.2.0/osm-gps-map-1.2.0.tar.gz : ddec11449f37b5dffb4bca134d024623897c6140af1f9981a8acc512dbf6a7a5
license    : GPL-2.0-or-later
component  : desktop.gtk
summary    : A Gtk+ Widget for Displaying OpenStreetMap tiles
description: |
    A Gtk+ Widget for Displaying OpenStreetMap tiles
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - gtk-doc
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
